version: '2'
services:
  dbms:
    container_name: bt_rdbms
    build:
        context: .
        dockerfile: database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  is-server:
    container_name: wso2-is
    build:
      context: .
      dockerfile: is-server/Dockerfile
    environment:
      - SLEEP=50
  mb-server:
    container_name: wso2-mb
    build:
      context: .
      dockerfile: mb-server/Dockerfile
    environment:
      - SLEEP=120
  esb-server:
    container_name: wso2-esb
    build:
      context: .
      dockerfile: esb-server/Dockerfile
    environment:
      - SLEEP=160
  das-server:
    container_name: wso2-das
    build:
      context: .
      dockerfile: das-server/Dockerfile
    environment:
      - SLEEP=200
  bps-server:
    container_name: wso2-bps
    build:
      context: .
      dockerfile: bps-server/Dockerfile
    environment:
      - SLEEP=250
  as-server:
    container_name: wso2-as
    build:
      context: .
      dockerfile: as-server/Dockerfile
    environment:
      - SLEEP=300
  am-server:
    container_name: wso2-am
    build:
      context: .
      dockerfile: am-server/Dockerfile
    environment:
      - SLEEP=350
    ports:
      - "9443:9443" #APIM
      - "9763:9763" #APIM
      - "8280:8280" #APIM
