version: '2'
services:
  dbms:
    container_name: bt_rdbms
    build:
        context: .
        dockerfile: database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  is-server:
    container_name: wso2-is
    build:
      context: .
      dockerfile: is-server/Dockerfile
    environment:
      - SLEEP=50
  mb-server:
    container_name: wso2-mb
    build:
      context: .
      dockerfile: mb-server/Dockerfile
    environment:
      - SLEEP=120
  esb-server:
    container_name: wso2-esb
    build:
      context: .
      dockerfile: esb-server/Dockerfile
    environment:
      - SLEEP=160
  das-server:
    container_name: wso2-das
    build:
      context: .
      dockerfile: das-server/Dockerfile
    environment:
      - SLEEP=200
  bps-server:
    container_name: wso2-bps
    build:
      context: .
      dockerfile: bps-server/Dockerfile
    environment:
      - SLEEP=250
  as-server:
    container_name: wso2-as
    build:
      context: .
      dockerfile: as-server/Dockerfile
    environment:
      - SLEEP=300
  am-server:
    container_name: wso2-am
    build:
      context: .
      dockerfile: am-server/Dockerfile
    environment:
      - SLEEP=350
    ports:
      - "9443:9443" #APIM
      - "9763:9763" #APIM
      - "8280:8280" #APIM
      - "8243:8243"
      - "5672:5672"
      - "8672:8672"
      - "1883:1883"
      - "8833:8833"
      - "7611:7611"
      - "8000:8000"
      - "10500:10500"
      - "9463:9463"
      - "9783:9783"
      - "1903:1903"
      - "5692:5692"
      - "8903:8903"
      - "8692:8692"
      - "9453:9453"
      - "9773:9773"
      - "9465:9465"
      - "8265:8265"
      - "8302:8302"
      - "10021:10021"
      - "9473:9473" #AS
      - "9793:9793" #AS
      - "7715:7715" #DAS
      - "7615:7615" #DAS
      - "9445:9445" #bps-server
      - "9765:9765" #bps-server
